chore(frontend): improve packages for npm
vaadin/fusion pull request #104
Opened 2021-09-09 14:57 UTC by Lodin

For each package:
- Add README file,
- Add LICENSE file,
- Use correct link to GitHub.

2021-09-10 06:01 UTC, haijian-vaadin requested changes

2021-09-10 11:32 UTC, platosha commented on frontend/packages/form/README.md
> +A tool to connect HTML forms with the Fusion backend seamlessly.
Perhaps should mention Lit as well.

2021-09-15 06:53 UTC, haijian-vaadin requested changes

2021-09-15 06:53 UTC, haijian-vaadin commented on frontend/packages/form/README.md
> +A set of utilities for building forms in TypeScript, including data binding, validation, code generation, backend integration, Lit directives, and more.
Lit is actually an essential part of @vaadin/form, maybe better to say
A set of utilities for building forms with TypeScript and [Lit](https://lit.dev/), including data binding, validation, code generation, backend integration, Lit directives, and more.

2021-09-15 07:35 UTC, haijian-vaadin approved these changes

2021-09-15 07:35 UTC, merged